### ISSUE TITLE
Korzystając z Traefika zmienić sposób wywoływania poszczególnych kontenerów

### ISSUE THREAD

**Issue by NaviteLogger** [IO-Lab2/Stack#2]
Co mam na myśli: żeby dotrzeć do dashboardu traefika, potrzebujemy udać się na 
http://epickaporownywarkabazwiedzyuczelni.rocks:8080/dashboard/#/
Okej, ale kto będzie pamietał który to port? Proponuję inaczej: 

Rozwiązanie 1:

każda domena ma możliwość ustawienia pod-domen. moglibyśmy uporządkować nasze kontenery tak, żeby zamiast portu można by wywołać np traefika za pomocą:
```
traefik.epickaporownywarkabazwiedzyuczelni.rocks
```
a api:
```
api.epickaporownywarkabazwiedzyuczelni.rocks
```

Rozwiązanie 2:

Jak 1. tylko z ..../ czyli
```
epickaporownywarkabazwiedzyuczelni.rocks/traefik
epickaporownywarkabazwiedzyuczelni.rocks/api
```

Takie rozwiązanie wyeliminuje potrzebę pamiętania który port to który i ułatwi nawigowanie po projekcie

**Comment by Cube0fDestiny** [comment]
działa api jest na api.epickaporownywarkabazwiedzyuczelni.rocks
a dashboard traefikowy na traefik.epickaporownywarkabazwiedzyuczelni.rocks
